server:
  port: 8025
spring:
  profiles:
    active: local #TODO: remove
  application:
    name: telegram-notifier
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.example.com
    port: 587
    username: YOUR_SMTP_USERNAME
    password: YOUR_SMTP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  rabbitmq:
    exchange: notifications.exchange
    queue: notifications.queue
    routing-key: notifications.routing-key
    dlx: notifications.dlx
    dlq: notifications.dlq
    dlq-routing-key: dead-letter
  mail:
    from: noreply@your-service.com
telegram:
  bot:
    token: YOUR_TELEGRAM_BOT_TOKEN
twilio:
  account-sid: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  auth-token: YOUR_TWILIO_AUTH_TOKEN
  from-number: +15005550006 # A valid Twilio phone number you own
feature-flags:
  sms:
    enabled: true # Set to false to disable SMS notifications
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
info:
  app:
    description: ${project.description} # From pom.xml
    version: ${project.version}       # From pom.xml
  contact:
    email: dev-team@example.com
logstash:
  host: localhost
  port: 5000
resilience4j:
  circuitbreaker:
    instances:
      email-service: &cb_defaults
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10 # Analyzes the last 10 calls
        failure-rate-threshold: 50 # If 50% of calls fail, the circuit opens
        wait-duration-in-open-state: 20s # Stays open for 20s before trying again
        permitted-number-of-calls-in-half-open-state: 3 # Allows 3 test calls in half-open state
        automatic-transition-from-open-to-half-open-enabled: true
      sms-service:
        <<: *cb_defaults # Use YAML anchors to avoid repetition
      telegram-service:
        <<: *cb_defaults
logging:
  level:
    # Set to TRACE to see detailed method entry/exit logs from the LoggingAspect
    # Set to INFO or higher to disable them.
    com.waquarshamsi.api.telegram_notifer.aspect: TRACE